# Adding and Subtracting Matrices in Python

# 1. Adding elements of the matrix

In [10]:
import numpy as np

# Creating first matrix
A = np.array([[1,2],[3,4]])

# creating second matrix
B = np.array([[4,5],[6,7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


# 2. Subtracting elements of matrices

In [11]:
# importing numpy as np
import numpy as np
 
 
# creating first matrix
A = np.array([[1, 2], [3, 4]])
 
# creating second matrix
B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]
