# Python – Matrix creation of n*n

# Using numpy

In [12]:
import numpy as np

#specify the size of the matrix
n = 4

#creates an n*n matrix 
matrix = np.zeros((n, n), dtype=int)
print(matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Using pandas DataFrame

In [13]:
import pandas as pd

# Create a 3x3 matrix with labeled rows and columns
n = 3
matrix = pd.DataFrame([[i * n + j + 1 for j in range(n)] for i in range(n)],
                      columns=['A', 'B', 'C'])
print(matrix)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
