# Transpose a matrix in Single line in Python

### Python Programs to Transpose a matrix using NumPy

In [3]:
import numpy
matrix = [[1, 2, 3], [4, 5, 6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


### Using “.T” after the variable

In [4]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print("\n")
print(matrix.T)

[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]
